# Generated by Django 5.1.15 on 2026-07-05 13:29

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='contracts.document')),
            ],
            options={
                'ordering': ['document_id', 'index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'index'), name='unique_chunk_per_document')],
            },
        ),
    ]
